spring:
  # 数据源配置（h2）
#  datasource:
#    master:
#      driver-class-name: org.h2.Driver
#      url: jdbc:h2:mem:sv_admin;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
#      #    url: jdbc:h2:file:./sv_admin;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
#      username: sa
#      password: 123
#    quartz:
#      driver-class-name: org.h2.Driver
#      url: jdbc:h2:mem:sv_admin;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
#      #    url: jdbc:h2:file:./sv_admin;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
#      username: sa
#      password: 123
#  h2:
#    console:
#      path: /h2
#      enabled: true
#      settings:
#        web-allow-others: true
#  sql:
#    init:
#      schema-locations:
#        - classpath:sql/h2/schema-h2.sql
#        - classpath:sql/h2/quartz-schema-h2.sql
#      data-locations: classpath:sql/h2/data-h2.sql
#      mode: embedded #h2内存模式才会进行初始化
#      encoding: utf-8

# 数据源配置（mysql）
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${JDBC_URL:jdbc:mysql://127.0.0.1:3306/sv_admin}
      username: ${JDBC_USERNAME:root}
      password: ${JDBC_PASSWORD:123456}
      hikari:
        pool-name: master
        maximum-pool-size: 5 #最大连接数
        minimum-idle: 1 #最小空闲连接数
        connection-timeout: 5000 #获取连接超时，5秒
        validation-timeout: 5000 #校验连接时超时，5秒
        keepalive-time: 120000 #保活时间，2分钟
        idle-timeout: 600000 #空闲时间，10分钟
        max-lifetime: 1200000 #最大存活时间，20分钟
    quartz:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${JDBC_URL:jdbc:mysql://127.0.0.1:3306/sv_admin}
      username: ${JDBC_USERNAME:root}
      password: ${JDBC_PASSWORD:123456}
      hikari:
        pool-name: quartz
        maximum-pool-size: 5 #最大连接数
        minimum-idle: 1 #最小空闲连接数
        connection-timeout: 5000 #获取连接超时，5秒
        validation-timeout: 5000 #校验连接时超时，5秒
        keepalive-time: 120000 #保活时间，2分钟
        idle-timeout: 600000 #空闲时间，10分钟
        max-lifetime: 1200000 #最大存活时间，20分钟

# 数据源配置（oracle）
#  datasource:
#    master:
#      driver-class-name: oracle.jdbc.OracleDriver
#      url: ${JDBC_URL:jdbc:oracle:thin:@//127.0.0.1:1521/XEPDB1}
#      username: ${JDBC_USERNAME:root}
#      password: ${JDBC_PASSWORD:123456}
#      hikari:
#        pool-name: master
#        maximum-pool-size: 5 #最大连接数
#        minimum-idle: 1 #最小空闲连接数
#        connection-timeout: 5000 #获取连接超时，5秒
#        validation-timeout: 5000 #校验连接时超时，5秒
#        keepalive-time: 120000 #保活时间，2分钟
#        idle-timeout: 600000 #空闲时间，10分钟
#        max-lifetime: 1200000 #最大存活时间，20分钟
#    quartz:
#      driver-class-name: oracle.jdbc.OracleDriver
#      url: ${JDBC_URL:jdbc:oracle:thin:@//127.0.0.1:1521/XEPDB1}
#      username: ${JDBC_USERNAME:root}
#      password: ${JDBC_PASSWORD:123456}
#      hikari:
#        pool-name: quartz
#        maximum-pool-size: 5 #最大连接数
#        minimum-idle: 1 #最小空闲连接数
#        connection-timeout: 5000 #获取连接超时，5秒
#        validation-timeout: 5000 #校验连接时超时，5秒
#        keepalive-time: 120000 #保活时间，2分钟
#        idle-timeout: 600000 #空闲时间，10分钟
#        max-lifetime: 1200000 #最大存活时间，20分钟

# 数据源配置（postgresql）
#  datasource:
#    master:
#      driver-class-name: org.postgresql.Driver
#      url: ${JDBC_URL:jdbc:postgresql://127.0.0.1:5432/sv_admin}
#      username: ${JDBC_USERNAME:root}
#      password: ${JDBC_PASSWORD:123456}
#      hikari:
#        pool-name: master
#        maximum-pool-size: 5 #最大连接数
#        minimum-idle: 1 #最小空闲连接数
#        connection-timeout: 5000 #获取连接超时，5秒
#        validation-timeout: 5000 #校验连接时超时，5秒
#        keepalive-time: 120000 #保活时间，2分钟
#        idle-timeout: 600000 #空闲时间，10分钟
#        max-lifetime: 1200000 #最大存活时间，20分钟
#    quartz:
#      driver-class-name: org.postgresql.Driver
#      url: ${JDBC_URL:jdbc:postgresql://127.0.0.1:5432/sv_admin}
#      username: ${JDBC_USERNAME:root}
#      password: ${JDBC_PASSWORD:123456}
#      hikari:
#        pool-name: quartz
#        maximum-pool-size: 5 #最大连接数
#        minimum-idle: 1 #最小空闲连接数
#        connection-timeout: 5000 #获取连接超时，5秒
#        validation-timeout: 5000 #校验连接时超时，5秒
#        keepalive-time: 120000 #保活时间，2分钟
#        idle-timeout: 600000 #空闲时间，10分钟
#        max-lifetime: 1200000 #最大存活时间，20分钟

# 指标监控
management:
  endpoints:
    web:
      exposure:
        include: "*"

# mybatis日志打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    "org.springframework.jdbc.support.JdbcTransactionManager": info #事务debug日志
    "org.apache.hc.client5.http": info #http client5 连接池日志
    "org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor": info #ai日志
